#lang racket

(require parser-tools/lex)
(require parser-tools/yacc)

;; LEXER
;; ----------------------------------------------------------------
(define my-lexer
  (lexer ((eof) "goodbye!")
         (any-char lexeme)))

(define my-port (open-input-file "script_c"))

(define-tokens my-tokens (a s d f))

(my-lexer my-port)
(my-lexer my-port)

(require parser-tools/yacc-to-scheme)
(trans "mdl.y")
;; ================================================================

;; PARSER
;; ----------------------------------------------------------------
(define-tokens t 
  (AMBIENT BASENAME BOX CAMERA CO COMMENT CONSTANTS DISPLAY DOUBLE FOCAL FRAMES GENERATE_RAYFILES LIGHT LINE MESH MOVE POP PUSH ROTATE SAVE SAVE_COORDS SAVE_KNOBS SCALE SET SETKNOBS SHADING SHADING_TYPE SPHERE STRING TEXTURE TORUS TWEEN VARY WEB))

(define-empty-tokens et ())

(define my-parser
  (parser 
   (start input) 
   (end EOF) 
   (error ___) 
   (tokens t et) 
   (grammar 
    (input 
     (() #f) 
     ((input command) #f)) 
    (command 
     ((COMMENT) #f) 
     ((LIGHT STRING DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((MOVE DOUBLE DOUBLE DOUBLE STRING) #f) 
     ((MOVE DOUBLE DOUBLE DOUBLE) #f) 
     ((CONSTANTS STRING DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((CONSTANTS STRING DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((SAVE_COORDS STRING) #f) 
     ((CAMERA DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE) #f)
     ((TEXTURE STRING DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((SPHERE DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((SPHERE DOUBLE DOUBLE DOUBLE DOUBLE STRING) #f) 
     ((SPHERE STRING DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((SPHERE STRING DOUBLE DOUBLE DOUBLE DOUBLE STRING) #f) 
     ((TORUS DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((TORUS DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE STRING) #f) 
     ((TORUS STRING DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((TORUS STRING DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE STRING) #f) 
     ((BOX DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((BOX DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE STRING) #f) 
     ((BOX STRING DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((BOX STRING DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE STRING) #f) 
     ((LINE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((LINE DOUBLE DOUBLE DOUBLE STRING DOUBLE DOUBLE DOUBLE) #f) 
     ((LINE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE STRING) #f) 
     ((LINE DOUBLE DOUBLE DOUBLE STRING DOUBLE DOUBLE DOUBLE STRING) #f) 
     ((LINE STRING DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((LINE STRING DOUBLE DOUBLE DOUBLE STRING DOUBLE DOUBLE DOUBLE) #f) 
     ((LINE STRING DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE DOUBLE STRING) #f) 
     ((LINE STRING DOUBLE DOUBLE DOUBLE STRING DOUBLE DOUBLE DOUBLE STRING) #f) 
     ((MESH CO STRING) #f) 
     ((MESH STRING CO STRING) #f) 
     ((MESH STRING CO STRING STRING) #f) 
     ((SET STRING DOUBLE) #f) 
     ((SCALE DOUBLE DOUBLE DOUBLE STRING) #f) 
     ((SCALE DOUBLE DOUBLE DOUBLE) #f) 
     ((ROTATE STRING DOUBLE STRING) #f) 
     ((ROTATE STRING DOUBLE) #f) 
     ((BASENAME STRING) #f) 
     ((SAVE_KNOBS STRING) #f) 
     ((TWEEN DOUBLE DOUBLE STRING STRING) #f) 
     ((FRAMES DOUBLE) #f) 
     ((VARY STRING DOUBLE DOUBLE DOUBLE DOUBLE) #f) 
     ((PUSH) #f) 
     ((GENERATE_RAYFILES) #f) 
     ((POP) #f) 
     ((SAVE STRING) #f) 
     ((SHADING SHADING_TYPE) #f) 
     ((SETKNOBS DOUBLE) #f) 
     ((FOCAL DOUBLE) #f) 
     ((DISPLAY) #f) 
     ((WEB) #f) 
     ((AMBIENT DOUBLE DOUBLE DOUBLE) #f)))))
;; ================================================================
